### ISSUE TITLE
question

### ISSUE THREAD

**Issue by NiceATC** [Ietu/pirate-perfection#1]
I'm currently using a VIP version, what's the difference between it and this one? and another thing what did you fix? my version seems to work well I wanted to know so I could fix it in my version since I modified the trainer a lot and I didn't want to just change it, but integrating your fixes would be of great help!

**Comment by Ietu** [comment]
There were a lot complaints on other PP version about crashing, including this version which I have been using for a long time. The crashing occurred every single time you get into the lobby. If you don't crash and it works, then you don't need to do anything about it.

About the features, I do not know what the VIP version has since I have not used that, but I know the Patron version was supposed to have the most latest features of the versions.
